// Generated by Hound from a deletion-minimal, paired-confirmed local replay plan.
// No model call, API key, cookie, original credential, fixture address, or private run path is required.
import { test, expect } from '@playwright/test';
import { randomBytes } from 'node:crypto';
import { startFixture } from '../apps/fixture/src/server.js';
import { BrowserExperiment, type ReplayPlan } from '../services/runtime/src/experiment.js';

const plan: ReplayPlan = {
  "version": 1,
  "steps": [
    {
      "action": {
        "actor": "alice",
        "kind": "fill",
        "recipe": {
          "by": "role",
          "role": "textbox",
          "name": [
            {
              "literal": "Workspace name"
            }
          ]
        },
        "value": {
          "ref": "trial_text"
        }
      },
      "before": [
        {
          "literal": "{\"documents\":[],\"invitations\":[],\"memberships\":[],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[]}"
        }
      ],
      "after": [
        {
          "literal": "{\"documents\":[],\"invitations\":[],\"memberships\":[],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[]}"
        }
      ],
      "http": [
        {
          "literal": "[]"
        }
      ]
    },
    {
      "action": {
        "actor": "alice",
        "kind": "click",
        "recipe": {
          "by": "role",
          "role": "button",
          "name": [
            {
              "literal": "Create workspace"
            }
          ]
        }
      },
      "before": [
        {
          "literal": "{\"documents\":[],\"invitations\":[],\"memberships\":[],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[]}"
        }
      ],
      "after": [
        {
          "literal": "{\"documents\":[{\"body\":\"A shared place for the next big idea.\",\"id\":\""
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"revision\":1,\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"invitations\":[],\"memberships\":[{\"actorKey\":\"alice\",\"role\":\"admin\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[{\"id\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"name\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\"}]}"
        }
      ],
      "http": [
        {
          "literal": "[{\"method\":\"GET\",\"path\":\"/api/workspaces/"
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"status\":200},{\"method\":\"POST\",\"path\":\"/api/workspaces\",\"status\":201}]"
        }
      ]
    },
    {
      "action": {
        "actor": "alice",
        "kind": "click",
        "recipe": {
          "by": "role",
          "role": "button",
          "name": [
            {
              "literal": "Send invitation"
            }
          ]
        }
      },
      "before": [
        {
          "literal": "{\"documents\":[{\"body\":\"A shared place for the next big idea.\",\"id\":\""
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"revision\":1,\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"invitations\":[],\"memberships\":[{\"actorKey\":\"alice\",\"role\":\"admin\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[{\"id\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"name\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\"}]}"
        }
      ],
      "after": [
        {
          "literal": "{\"documents\":[{\"body\":\"A shared place for the next big idea.\",\"id\":\""
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"revision\":1,\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"invitations\":[{\"id\":\""
        },
        {
          "ref": "invitation_1"
        },
        {
          "literal": "\",\"recipient\":\"bob\",\"status\":\"pending\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"memberships\":[{\"actorKey\":\"alice\",\"role\":\"admin\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[{\"id\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"name\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\"}]}"
        }
      ],
      "http": [
        {
          "literal": "[{\"method\":\"POST\",\"path\":\"/api/workspaces/"
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "/invitations\",\"status\":201}]"
        }
      ]
    },
    {
      "action": {
        "actor": "bob",
        "kind": "click",
        "recipe": {
          "by": "role",
          "role": "button",
          "name": [
            {
              "literal": "Refresh"
            }
          ]
        }
      },
      "before": [
        {
          "literal": "{\"documents\":[{\"body\":\"A shared place for the next big idea.\",\"id\":\""
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"revision\":1,\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"invitations\":[{\"id\":\""
        },
        {
          "ref": "invitation_1"
        },
        {
          "literal": "\",\"recipient\":\"bob\",\"status\":\"pending\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"memberships\":[{\"actorKey\":\"alice\",\"role\":\"admin\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[{\"id\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"name\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\"}]}"
        }
      ],
      "after": [
        {
          "literal": "{\"documents\":[{\"body\":\"A shared place for the next big idea.\",\"id\":\""
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"revision\":1,\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"invitations\":[{\"id\":\""
        },
        {
          "ref": "invitation_1"
        },
        {
          "literal": "\",\"recipient\":\"bob\",\"status\":\"pending\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"memberships\":[{\"actorKey\":\"alice\",\"role\":\"admin\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[{\"id\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"name\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\"}]}"
        }
      ],
      "http": [
        {
          "literal": "[{\"method\":\"GET\",\"path\":\"/api/invitations\",\"status\":200},{\"method\":\"GET\",\"path\":\"/api/workspaces\",\"status\":200}]"
        }
      ]
    },
    {
      "action": {
        "actor": "bob",
        "kind": "click",
        "recipe": {
          "by": "role",
          "role": "button",
          "name": [
            {
              "literal": "Accept invitation"
            }
          ]
        }
      },
      "before": [
        {
          "literal": "{\"documents\":[{\"body\":\"A shared place for the next big idea.\",\"id\":\""
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"revision\":1,\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"invitations\":[{\"id\":\""
        },
        {
          "ref": "invitation_1"
        },
        {
          "literal": "\",\"recipient\":\"bob\",\"status\":\"pending\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"memberships\":[{\"actorKey\":\"alice\",\"role\":\"admin\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[{\"id\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"name\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\"}]}"
        }
      ],
      "after": [
        {
          "literal": "{\"documents\":[{\"body\":\"A shared place for the next big idea.\",\"id\":\""
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"revision\":1,\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"invitations\":[{\"id\":\""
        },
        {
          "ref": "invitation_1"
        },
        {
          "literal": "\",\"recipient\":\"bob\",\"status\":\"accepted\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"memberships\":[{\"actorKey\":\"alice\",\"role\":\"admin\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"},{\"actorKey\":\"bob\",\"role\":\"member\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[{\"id\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"name\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\"}]}"
        }
      ],
      "http": [
        {
          "literal": "[{\"method\":\"GET\",\"path\":\"/api/invitations\",\"status\":200},{\"method\":\"GET\",\"path\":\"/api/workspaces\",\"status\":200},{\"method\":\"POST\",\"path\":\"/api/invitations/"
        },
        {
          "ref": "invitation_1"
        },
        {
          "literal": "/accept\",\"status\":200}]"
        }
      ]
    },
    {
      "action": {
        "actor": "bob",
        "kind": "click",
        "recipe": {
          "by": "role",
          "role": "link",
          "name": [
            {
              "ref": "trial_text"
            },
            {
              "literal": " Open workspace"
            }
          ]
        }
      },
      "before": [
        {
          "literal": "{\"documents\":[{\"body\":\"A shared place for the next big idea.\",\"id\":\""
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"revision\":1,\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"invitations\":[{\"id\":\""
        },
        {
          "ref": "invitation_1"
        },
        {
          "literal": "\",\"recipient\":\"bob\",\"status\":\"accepted\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"memberships\":[{\"actorKey\":\"alice\",\"role\":\"admin\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"},{\"actorKey\":\"bob\",\"role\":\"member\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[{\"id\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"name\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\"}]}"
        }
      ],
      "after": [
        {
          "literal": "{\"documents\":[{\"body\":\"A shared place for the next big idea.\",\"id\":\""
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"revision\":1,\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"invitations\":[{\"id\":\""
        },
        {
          "ref": "invitation_1"
        },
        {
          "literal": "\",\"recipient\":\"bob\",\"status\":\"accepted\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"memberships\":[{\"actorKey\":\"alice\",\"role\":\"admin\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"},{\"actorKey\":\"bob\",\"role\":\"member\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[{\"id\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"name\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\"}]}"
        }
      ],
      "http": [
        {
          "literal": "[{\"method\":\"GET\",\"path\":\"/api/workspaces/"
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"status\":200}]"
        }
      ]
    },
    {
      "action": {
        "actor": "bob",
        "kind": "click",
        "recipe": {
          "by": "role",
          "role": "link",
          "name": [
            {
              "literal": "TEAM NOTEBOOK Shared document Ideas, plans, and a little room to think. Open document"
            }
          ]
        }
      },
      "before": [
        {
          "literal": "{\"documents\":[{\"body\":\"A shared place for the next big idea.\",\"id\":\""
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"revision\":1,\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"invitations\":[{\"id\":\""
        },
        {
          "ref": "invitation_1"
        },
        {
          "literal": "\",\"recipient\":\"bob\",\"status\":\"accepted\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"memberships\":[{\"actorKey\":\"alice\",\"role\":\"admin\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"},{\"actorKey\":\"bob\",\"role\":\"member\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[{\"id\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"name\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\"}]}"
        }
      ],
      "after": [
        {
          "literal": "{\"documents\":[{\"body\":\"A shared place for the next big idea.\",\"id\":\""
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"revision\":1,\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"invitations\":[{\"id\":\""
        },
        {
          "ref": "invitation_1"
        },
        {
          "literal": "\",\"recipient\":\"bob\",\"status\":\"accepted\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"memberships\":[{\"actorKey\":\"alice\",\"role\":\"admin\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"},{\"actorKey\":\"bob\",\"role\":\"member\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[{\"id\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"name\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\"}]}"
        }
      ],
      "http": [
        {
          "literal": "[{\"method\":\"GET\",\"path\":\"/api/documents/"
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"status\":200}]"
        }
      ]
    },
    {
      "action": {
        "actor": "alice",
        "kind": "click",
        "recipe": {
          "by": "role",
          "role": "button",
          "name": [
            {
              "literal": "Refresh members"
            }
          ]
        }
      },
      "before": [
        {
          "literal": "{\"documents\":[{\"body\":\"A shared place for the next big idea.\",\"id\":\""
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"revision\":1,\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"invitations\":[{\"id\":\""
        },
        {
          "ref": "invitation_1"
        },
        {
          "literal": "\",\"recipient\":\"bob\",\"status\":\"accepted\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"memberships\":[{\"actorKey\":\"alice\",\"role\":\"admin\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"},{\"actorKey\":\"bob\",\"role\":\"member\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[{\"id\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"name\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\"}]}"
        }
      ],
      "after": [
        {
          "literal": "{\"documents\":[{\"body\":\"A shared place for the next big idea.\",\"id\":\""
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"revision\":1,\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"invitations\":[{\"id\":\""
        },
        {
          "ref": "invitation_1"
        },
        {
          "literal": "\",\"recipient\":\"bob\",\"status\":\"accepted\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"memberships\":[{\"actorKey\":\"alice\",\"role\":\"admin\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"},{\"actorKey\":\"bob\",\"role\":\"member\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[{\"id\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"name\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\"}]}"
        }
      ],
      "http": [
        {
          "literal": "[{\"method\":\"GET\",\"path\":\"/api/workspaces/"
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"status\":200}]"
        }
      ]
    },
    {
      "action": {
        "actor": "alice",
        "kind": "click",
        "recipe": {
          "by": "role",
          "role": "button",
          "name": [
            {
              "literal": "Remove Bob"
            }
          ]
        }
      },
      "before": [
        {
          "literal": "{\"documents\":[{\"body\":\"A shared place for the next big idea.\",\"id\":\""
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"revision\":1,\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"invitations\":[{\"id\":\""
        },
        {
          "ref": "invitation_1"
        },
        {
          "literal": "\",\"recipient\":\"bob\",\"status\":\"accepted\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"memberships\":[{\"actorKey\":\"alice\",\"role\":\"admin\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"},{\"actorKey\":\"bob\",\"role\":\"member\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[{\"id\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"name\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\"}]}"
        }
      ],
      "after": [
        {
          "literal": "{\"documents\":[{\"body\":\"A shared place for the next big idea.\",\"id\":\""
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"revision\":1,\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"invitations\":[{\"id\":\""
        },
        {
          "ref": "invitation_1"
        },
        {
          "literal": "\",\"recipient\":\"bob\",\"status\":\"accepted\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"memberships\":[{\"actorKey\":\"alice\",\"role\":\"admin\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[{\"id\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"name\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\"}]}"
        }
      ],
      "http": [
        {
          "literal": "[{\"method\":\"DELETE\",\"path\":\"/api/workspaces/"
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "/members/bob\",\"status\":204},{\"method\":\"GET\",\"path\":\"/api/workspaces/"
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"status\":200}]"
        }
      ]
    },
    {
      "action": {
        "actor": "bob",
        "kind": "fill",
        "recipe": {
          "by": "role",
          "role": "textbox",
          "name": [
            {
              "literal": "Document body"
            }
          ]
        },
        "value": {
          "ref": "trial_text"
        }
      },
      "before": [
        {
          "literal": "{\"documents\":[{\"body\":\"A shared place for the next big idea.\",\"id\":\""
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"revision\":1,\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"invitations\":[{\"id\":\""
        },
        {
          "ref": "invitation_1"
        },
        {
          "literal": "\",\"recipient\":\"bob\",\"status\":\"accepted\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"memberships\":[{\"actorKey\":\"alice\",\"role\":\"admin\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[{\"id\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"name\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\"}]}"
        }
      ],
      "after": [
        {
          "literal": "{\"documents\":[{\"body\":\"A shared place for the next big idea.\",\"id\":\""
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"revision\":1,\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"invitations\":[{\"id\":\""
        },
        {
          "ref": "invitation_1"
        },
        {
          "literal": "\",\"recipient\":\"bob\",\"status\":\"accepted\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"memberships\":[{\"actorKey\":\"alice\",\"role\":\"admin\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[{\"id\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"name\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\"}]}"
        }
      ],
      "http": [
        {
          "literal": "[]"
        }
      ]
    },
    {
      "action": {
        "actor": "bob",
        "kind": "click",
        "recipe": {
          "by": "role",
          "role": "button",
          "name": [
            {
              "literal": "Save document"
            }
          ]
        }
      },
      "before": [
        {
          "literal": "{\"documents\":[{\"body\":\"A shared place for the next big idea.\",\"id\":\""
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"revision\":1,\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"invitations\":[{\"id\":\""
        },
        {
          "ref": "invitation_1"
        },
        {
          "literal": "\",\"recipient\":\"bob\",\"status\":\"accepted\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"memberships\":[{\"actorKey\":\"alice\",\"role\":\"admin\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[{\"id\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"name\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\"}]}"
        }
      ],
      "after": [
        {
          "literal": "{\"documents\":[{\"body\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\",\"id\":\""
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"revision\":2,\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"invitations\":[{\"id\":\""
        },
        {
          "ref": "invitation_1"
        },
        {
          "literal": "\",\"recipient\":\"bob\",\"status\":\"accepted\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"memberships\":[{\"actorKey\":\"alice\",\"role\":\"admin\",\"workspaceId\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\"}],\"users\":[{\"actorKey\":\"alice\",\"displayName\":\"Alice\"},{\"actorKey\":\"bob\",\"displayName\":\"Bob\"}],\"workspaces\":[{\"id\":\""
        },
        {
          "ref": "workspace_1"
        },
        {
          "literal": "\",\"name\":\""
        },
        {
          "ref": "trial_text"
        },
        {
          "literal": "\"}]}"
        }
      ],
      "http": [
        {
          "literal": "[{\"method\":\"PATCH\",\"path\":\"/api/documents/"
        },
        {
          "ref": "document_1"
        },
        {
          "literal": "\",\"status\":200}]"
        }
      ]
    }
  ],
  "probeActor": "bob",
  "probeResource": "document_1",
  "id": "75afe58f40035125ac570029ed839a30ce9863190bfedfb515657b4a997a8bc5"
};
const credentials = { alice: 'generated-regression-alice', bob: 'generated-regression-bob' };

test('removed workspace member cannot modify a document through a retained session', async ({ browser }) => {
  test.setTimeout(90_000);
  const requestedMode = process.env.HOUND_FIXTURE_MODE ?? 'baseline';
  if (requestedMode !== 'baseline' && requestedMode !== 'stale-write') throw new Error('HOUND_FIXTURE_MODE must be baseline or stale-write');
  const harnessKey = randomBytes(32).toString('hex');
  const fixture = await startFixture({ mode: requestedMode, credentials, harnessKey });
  let run: BrowserExperiment | undefined;
  try {
    run = await BrowserExperiment.open(browser, { ...fixture, credentials, harnessKey, maxDecisions: plan.steps.length, deadlineMs: 60_000 });
    const result = await run.replay(plan);
    expect(result.setupEquivalent, result.reason).toBe(true);
    expect(result.actor).toBe('bob');
    expect(result.resourceRef).toBe('document_1');
    expect(result.result).toBe('denied');
  } finally {
    await run?.close();
    await fixture.close();
  }
});
