import type { ReplayPlan } from './experiment.js';

const safeJson = (value: unknown) => JSON.stringify(value, null, 2).replaceAll('\u2028', '\\u2028').replaceAll('\u2029', '\\u2029');

/** Emits a local, model-free Playwright regression from a confirmed normalized plan. */
export function exportPlaywrightRegression(plan: ReplayPlan) {
  if (plan.version !== 1 || !plan.steps.length || plan.steps.length > 120 || plan.probeActor !== 'bob' || plan.probeResource !== 'document_1') {
    throw new Error('unsupported_export_plan');
  }
  const embedded = safeJson(plan);
  return `// Generated by Hound from a deletion-minimal, paired-confirmed local replay plan.
// No model call, API key, cookie, original credential, fixture address, or private run path is required.
import { test, expect } from '@playwright/test';
import { randomBytes } from 'node:crypto';
import { startFixture } from '../apps/fixture/src/server.js';
import { BrowserExperiment, type ReplayPlan } from '../services/runtime/src/experiment.js';

const plan: ReplayPlan = ${embedded};
const credentials = { alice: 'generated-regression-alice', bob: 'generated-regression-bob' };

test('removed workspace member cannot modify a document through a retained session', async ({ browser }) => {
  test.setTimeout(90_000);
  const requestedMode = process.env.HOUND_FIXTURE_MODE ?? 'baseline';
  if (requestedMode !== 'baseline' && requestedMode !== 'stale-write') throw new Error('HOUND_FIXTURE_MODE must be baseline or stale-write');
  const harnessKey = randomBytes(32).toString('hex');
  const fixture = await startFixture({ mode: requestedMode, credentials, harnessKey });
  let run: BrowserExperiment | undefined;
  try {
    run = await BrowserExperiment.open(browser, { ...fixture, credentials, harnessKey, maxDecisions: plan.steps.length, deadlineMs: 60_000 });
    const result = await run.replay(plan);
    expect(result.setupEquivalent, result.reason).toBe(true);
    expect(result.actor).toBe('bob');
    expect(result.resourceRef).toBe('document_1');
    expect(result.result).toBe('denied');
  } finally {
    await run?.close();
    await fixture.close();
  }
});
`;
}
